apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-certs
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: nats
  project: null-cloud
  source:
    path: deployments/manifests/nats
    repoURL: https://github.com/null-channel/eddington/
    targetRevision: HEAD
  syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true