apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 40.3.1
    helm:
      releaseName: kube-prometheus-stack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring 
