version: "3.7"

#deploy dockerfile and buildkitd on the same network 
services:
  buildkit:
    image: moby/buildkit 
    privileged: true
    volumes:
      - /var/lib/buildkit
    networks:
      - buildkit

  container-builder:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: container-builder
    image: dockerfile
    networks:
      - buildkit
    depends_on:
      - buildkit 


networks:
  buildkit:


