version: "3.7"

#deploy dockerfile and buildkitd on the same network 
services:
  buildkitd:
    image: moby/buildkit 
    privileged: true
    hostname: buildkitd
    command: ["--addr", "tcp://0.0.0.0:4000"]  # Replace "1234" with the desired TCP port number
    ports:
      - "4000:4000"
    volumes:
      - /var/lib/buildkit
    networks:
      - buildkit

  container-builder:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: container-builder
    image: dockerfile
    networks:
      - buildkit
    depends_on:
      - buildkitd

networks:
  buildkit:

  

