---
kind: Namespace
apiVersion: v1
metadata:
  name: null-bot
  labels:
    name: null-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: null-bot
  namespace: null-bot
spec:
  selector:
    matchLabels:
      app: null-bot
  template:
    metadata:
      labels:
        app: null-bot
    spec:
      containers: 
      - name: null-bot
        image: nullchannel/null-bot:f2a21af21bb788422884119ee57f2a3f27bdc3c6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: null-bot-token
                key: token
                optional: false
          - name: GUILD_ID
            valueFrom:
              secretKeyRef:
                name: null-bot-token
                key: guild_id
                optional: false

