apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: our-app-bob
  namespace: user-id
spec:
  hosts:
  - "*"
  gateways:
  - nullcloud-gateway
  http:
  - name: user-id/bob
    match:
      - name: "user-id-our-app-bob"
        uri:
          prefix: "/user-id/our-app/bob/"
    route:
      - destination:
          host: bob
          port:
            number: 80
