---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nullapp.io.nullcloud
  resources:
  - nullapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nullapp.io.nullcloud
  resources:
  - nullapplications/finalizers
  verbs:
  - update
- apiGroups:
  - nullapp.io.nullcloud
  resources:
  - nullapplications/status
  verbs:
  - get
  - patch
  - update
