apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: null-bot
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: null-bot
  project: null-cloud
  source:
    path: deployments/null-bot/overlays/prod
    repoURL: https://github.com/null-channel/nullcloud-deployments/
    targetRevision: HEAD
  syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true